# Generated by Django 2.1.7 on 2019-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190722_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default='default-profile-picture.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='trader_id',
            field=models.IntegerField(default=3533800085),
        ),
    ]
